// Code generated by scripts/generate-house-contracts.py; DO NOT EDIT.
package grpc

import (
	"context"
	"encoding/json"
	pb "github.com/ZheglY/SmartQuarter/services/identity-service/internal/gen/smartquarter/identity/v1"
	"github.com/ZheglY/SmartQuarter/services/identity-service/internal/house"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type HouseHandler struct {
	pb.UnimplementedHouseServiceServer
	Workflow *house.Service
}

func (h *HouseHandler) call(ctx context.Context, op string, req, res proto.Message) error {
	raw, e := (protojson.MarshalOptions{UseProtoNames: true, EmitDefaultValues: true}).Marshal(req)
	if e != nil {
		return status.Error(codes.InvalidArgument, "invalid command")
	}
	var c house.Command
	if json.Unmarshal(raw, &c) != nil {
		return status.Error(codes.InvalidArgument, "invalid command")
	}
	data, e := h.Workflow.Execute(ctx, op, c)
	if e != nil {
		return e
	}
	if e = (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(data, res); e != nil {
		return status.Error(codes.Internal, "invalid workflow response")
	}
	return nil
}
func (h *HouseHandler) ListPlatformUsers(ctx context.Context, req *pb.ListPlatformUsersRequest) (*pb.PlatformUserList, error) {
	res := new(pb.PlatformUserList)
	err := h.call(ctx, "ListPlatformUsers", req, res)
	return res, err
}
func (h *HouseHandler) GrantChairmanPermission(ctx context.Context, req *pb.GrantChairmanPermissionRequest) (*pb.PlatformUser, error) {
	res := new(pb.PlatformUser)
	err := h.call(ctx, "GrantChairmanPermission", req, res)
	return res, err
}
func (h *HouseHandler) RevokeChairmanPermission(ctx context.Context, req *pb.RevokeChairmanPermissionRequest) (*pb.PlatformUser, error) {
	res := new(pb.PlatformUser)
	err := h.call(ctx, "RevokeChairmanPermission", req, res)
	return res, err
}
func (h *HouseHandler) ListAdminHouses(ctx context.Context, req *pb.ListAdminHousesRequest) (*pb.AdminHouseList, error) {
	res := new(pb.AdminHouseList)
	err := h.call(ctx, "ListAdminHouses", req, res)
	return res, err
}
func (h *HouseHandler) AssignHouseChairman(ctx context.Context, req *pb.AssignHouseChairmanRequest) (*pb.AdminHouse, error) {
	res := new(pb.AdminHouse)
	err := h.call(ctx, "AssignHouseChairman", req, res)
	return res, err
}
func (h *HouseHandler) RemoveHouseChairman(ctx context.Context, req *pb.RemoveHouseChairmanRequest) (*pb.AdminHouse, error) {
	res := new(pb.AdminHouse)
	err := h.call(ctx, "RemoveHouseChairman", req, res)
	return res, err
}
func (h *HouseHandler) CreateHouseRegistration(ctx context.Context, req *pb.CreateHouseRegistrationRequest) (*pb.HouseRegistration, error) {
	res := new(pb.HouseRegistration)
	err := h.call(ctx, "CreateHouseRegistration", req, res)
	return res, err
}
func (h *HouseHandler) GetHouseRegistration(ctx context.Context, req *pb.GetHouseRegistrationRequest) (*pb.HouseRegistration, error) {
	res := new(pb.HouseRegistration)
	err := h.call(ctx, "GetHouseRegistration", req, res)
	return res, err
}
func (h *HouseHandler) ListMyHouseRegistrations(ctx context.Context, req *pb.ListMyHouseRegistrationsRequest) (*pb.HouseRegistrationList, error) {
	res := new(pb.HouseRegistrationList)
	err := h.call(ctx, "ListMyHouseRegistrations", req, res)
	return res, err
}
func (h *HouseHandler) CancelHouseRegistration(ctx context.Context, req *pb.CancelHouseRegistrationRequest) (*pb.HouseRegistration, error) {
	res := new(pb.HouseRegistration)
	err := h.call(ctx, "CancelHouseRegistration", req, res)
	return res, err
}
func (h *HouseHandler) ListPendingHouseRegistrations(ctx context.Context, req *pb.ListPendingHouseRegistrationsRequest) (*pb.HouseRegistrationList, error) {
	res := new(pb.HouseRegistrationList)
	err := h.call(ctx, "ListPendingHouseRegistrations", req, res)
	return res, err
}
func (h *HouseHandler) ApproveHouseRegistration(ctx context.Context, req *pb.ApproveHouseRegistrationRequest) (*pb.HouseRegistration, error) {
	res := new(pb.HouseRegistration)
	err := h.call(ctx, "ApproveHouseRegistration", req, res)
	return res, err
}
func (h *HouseHandler) RejectHouseRegistration(ctx context.Context, req *pb.RejectHouseRegistrationRequest) (*pb.HouseRegistration, error) {
	res := new(pb.HouseRegistration)
	err := h.call(ctx, "RejectHouseRegistration", req, res)
	return res, err
}
func (h *HouseHandler) SearchHouses(ctx context.Context, req *pb.SearchHousesRequest) (*pb.HouseSearchResult, error) {
	res := new(pb.HouseSearchResult)
	err := h.call(ctx, "SearchHouses", req, res)
	return res, err
}
func (h *HouseHandler) CreateJoinRequest(ctx context.Context, req *pb.CreateJoinRequestRequest) (*pb.JoinRequest, error) {
	res := new(pb.JoinRequest)
	err := h.call(ctx, "CreateJoinRequest", req, res)
	return res, err
}
func (h *HouseHandler) ListMyJoinRequests(ctx context.Context, req *pb.ListMyJoinRequestsRequest) (*pb.JoinRequestList, error) {
	res := new(pb.JoinRequestList)
	err := h.call(ctx, "ListMyJoinRequests", req, res)
	return res, err
}
func (h *HouseHandler) CancelJoinRequest(ctx context.Context, req *pb.CancelJoinRequestRequest) (*pb.JoinRequest, error) {
	res := new(pb.JoinRequest)
	err := h.call(ctx, "CancelJoinRequest", req, res)
	return res, err
}
func (h *HouseHandler) ListHouseJoinRequests(ctx context.Context, req *pb.ListHouseJoinRequestsRequest) (*pb.JoinRequestList, error) {
	res := new(pb.JoinRequestList)
	err := h.call(ctx, "ListHouseJoinRequests", req, res)
	return res, err
}
func (h *HouseHandler) ApproveJoinRequest(ctx context.Context, req *pb.ApproveJoinRequestRequest) (*pb.JoinRequest, error) {
	res := new(pb.JoinRequest)
	err := h.call(ctx, "ApproveJoinRequest", req, res)
	return res, err
}
func (h *HouseHandler) RejectJoinRequest(ctx context.Context, req *pb.RejectJoinRequestRequest) (*pb.JoinRequest, error) {
	res := new(pb.JoinRequest)
	err := h.call(ctx, "RejectJoinRequest", req, res)
	return res, err
}
func (h *HouseHandler) CreateHouseInvitation(ctx context.Context, req *pb.CreateHouseInvitationRequest) (*pb.CreatedInvitation, error) {
	res := new(pb.CreatedInvitation)
	err := h.call(ctx, "CreateHouseInvitation", req, res)
	return res, err
}
func (h *HouseHandler) ListHouseInvitations(ctx context.Context, req *pb.ListHouseInvitationsRequest) (*pb.HouseInvitationList, error) {
	res := new(pb.HouseInvitationList)
	err := h.call(ctx, "ListHouseInvitations", req, res)
	return res, err
}
func (h *HouseHandler) GetHouseInvitation(ctx context.Context, req *pb.GetHouseInvitationRequest) (*pb.HouseInvitation, error) {
	res := new(pb.HouseInvitation)
	err := h.call(ctx, "GetHouseInvitation", req, res)
	return res, err
}
func (h *HouseHandler) RevokeHouseInvitation(ctx context.Context, req *pb.RevokeHouseInvitationRequest) (*pb.HouseInvitation, error) {
	res := new(pb.HouseInvitation)
	err := h.call(ctx, "RevokeHouseInvitation", req, res)
	return res, err
}
func (h *HouseHandler) RedeemHouseInvitation(ctx context.Context, req *pb.RedeemHouseInvitationRequest) (*pb.JoinRequest, error) {
	res := new(pb.JoinRequest)
	err := h.call(ctx, "RedeemHouseInvitation", req, res)
	return res, err
}
func (h *HouseHandler) PreviewHouseInvitation(ctx context.Context, req *pb.PreviewHouseInvitationRequest) (*pb.HouseSummary, error) {
	res := new(pb.HouseSummary)
	err := h.call(ctx, "PreviewHouseInvitation", req, res)
	return res, err
}
func (h *HouseHandler) CreateChairmanTransfer(ctx context.Context, req *pb.CreateChairmanTransferRequest) (*pb.ChairmanTransfer, error) {
	res := new(pb.ChairmanTransfer)
	err := h.call(ctx, "CreateChairmanTransfer", req, res)
	return res, err
}
func (h *HouseHandler) ListChairmanTransfers(ctx context.Context, req *pb.ListChairmanTransfersRequest) (*pb.ChairmanTransferList, error) {
	res := new(pb.ChairmanTransferList)
	err := h.call(ctx, "ListChairmanTransfers", req, res)
	return res, err
}
func (h *HouseHandler) AcceptChairmanTransfer(ctx context.Context, req *pb.AcceptChairmanTransferRequest) (*pb.ChairmanTransfer, error) {
	res := new(pb.ChairmanTransfer)
	err := h.call(ctx, "AcceptChairmanTransfer", req, res)
	return res, err
}
func (h *HouseHandler) RejectChairmanTransfer(ctx context.Context, req *pb.RejectChairmanTransferRequest) (*pb.ChairmanTransfer, error) {
	res := new(pb.ChairmanTransfer)
	err := h.call(ctx, "RejectChairmanTransfer", req, res)
	return res, err
}
func (h *HouseHandler) CancelChairmanTransfer(ctx context.Context, req *pb.CancelChairmanTransferRequest) (*pb.ChairmanTransfer, error) {
	res := new(pb.ChairmanTransfer)
	err := h.call(ctx, "CancelChairmanTransfer", req, res)
	return res, err
}
func (h *HouseHandler) ListHouseMembers(ctx context.Context, req *pb.ListHouseMembersRequest) (*pb.HouseMemberList, error) {
	res := new(pb.HouseMemberList)
	err := h.call(ctx, "ListHouseMembers", req, res)
	return res, err
}
func (h *HouseHandler) DeactivateMembership(ctx context.Context, req *pb.DeactivateMembershipRequest) (*pb.HouseMember, error) {
	res := new(pb.HouseMember)
	err := h.call(ctx, "DeactivateMembership", req, res)
	return res, err
}
func (h *HouseHandler) ReactivateMembership(ctx context.Context, req *pb.ReactivateMembershipRequest) (*pb.HouseMember, error) {
	res := new(pb.HouseMember)
	err := h.call(ctx, "ReactivateMembership", req, res)
	return res, err
}
func (h *HouseHandler) RemoveMembership(ctx context.Context, req *pb.RemoveMembershipRequest) (*pb.HouseMember, error) {
	res := new(pb.HouseMember)
	err := h.call(ctx, "RemoveMembership", req, res)
	return res, err
}
func (h *HouseHandler) GetHouseAccessState(ctx context.Context, req *pb.GetHouseAccessStateRequest) (*pb.HouseAccessState, error) {
	res := new(pb.HouseAccessState)
	err := h.call(ctx, "GetHouseAccessState", req, res)
	return res, err
}
func (h *HouseHandler) GetNotificationPreferences(ctx context.Context, req *pb.GetNotificationPreferencesRequest) (*pb.NotificationPreferences, error) {
	res := new(pb.NotificationPreferences)
	err := h.call(ctx, "GetNotificationPreferences", req, res)
	return res, err
}
func (h *HouseHandler) UpdateNotificationPreferences(ctx context.Context, req *pb.UpdateNotificationPreferencesRequest) (*pb.NotificationPreferences, error) {
	res := new(pb.NotificationPreferences)
	err := h.call(ctx, "UpdateNotificationPreferences", req, res)
	return res, err
}
func (h *HouseHandler) ListNotificationRecipients(ctx context.Context, req *pb.ListNotificationRecipientsRequest) (*pb.NotificationRecipientList, error) {
	res := new(pb.NotificationRecipientList)
	err := h.call(ctx, "ListNotificationRecipients", req, res)
	return res, err
}
