// Generated by scripts/generate-house-web.py.
import { z } from 'zod';
import { request } from './client';
const HouseRegistrationStatusSchema = z.enum(["HOUSE_REGISTRATION_STATUS_PENDING", "HOUSE_REGISTRATION_STATUS_APPROVED", "HOUSE_REGISTRATION_STATUS_REJECTED", "HOUSE_REGISTRATION_STATUS_CANCELLED"]);
const JoinRequestStatusSchema = z.enum(["JOIN_REQUEST_STATUS_PENDING", "JOIN_REQUEST_STATUS_APPROVED", "JOIN_REQUEST_STATUS_REJECTED", "JOIN_REQUEST_STATUS_CANCELLED"]);
const InvitationStatusSchema = z.enum(["INVITATION_STATUS_ACTIVE", "INVITATION_STATUS_EXPIRED", "INVITATION_STATUS_REVOKED", "INVITATION_STATUS_EXHAUSTED"]);
const ChairmanTransferStatusSchema = z.enum(["CHAIRMAN_TRANSFER_STATUS_PENDING", "CHAIRMAN_TRANSFER_STATUS_ACCEPTED", "CHAIRMAN_TRANSFER_STATUS_REJECTED", "CHAIRMAN_TRANSFER_STATUS_CANCELLED", "CHAIRMAN_TRANSFER_STATUS_EXPIRED"]);
const JoinRequestSourceSchema = z.enum(["JOIN_REQUEST_SOURCE_SEARCH", "JOIN_REQUEST_SOURCE_INVITE", "JOIN_REQUEST_SOURCE_ADMIN"]);
export const PlatformUserSchema = z.object({
 id: z.string().uuid(),
 display_name: z.string(),
 max_user_id: z.string(),
 can_register_house: z.boolean(),
 managed_houses: z.number().int(),
});
export type PlatformUser = z.infer<typeof PlatformUserSchema>;
export const PlatformUserListSchema = z.object({
 items: PlatformUserSchema.array(),
});
export type PlatformUserList = z.infer<typeof PlatformUserListSchema>;
export const AdminHouseSchema = z.object({
 id: z.string().uuid(),
 name: z.string(),
 address: z.string(),
 city: z.string(),
 chairman_user_id: z.union([z.string().uuid(),z.literal('')]),
 chairman_display_name: z.string(),
});
export type AdminHouse = z.infer<typeof AdminHouseSchema>;
export const AdminHouseListSchema = z.object({
 items: AdminHouseSchema.array(),
});
export type AdminHouseList = z.infer<typeof AdminHouseListSchema>;
export const HouseRegistrationSchema = z.object({
 id: z.string().uuid(),
 applicant_user_id: z.string().uuid(),
 requested_name: z.string(),
 original_address: z.string(),
 city: z.string(),
 status: HouseRegistrationStatusSchema,
 resulting_house_id: z.union([z.string().uuid(),z.literal('')]),
 rejection_reason: z.string(),
 created_at: z.string().datetime({offset:true}).nullable().optional(),
 reviewed_at: z.string().datetime({offset:true}).nullable().optional(),
 applicant_display_name: z.string(),
});
export type HouseRegistration = z.infer<typeof HouseRegistrationSchema>;
export const JoinRequestSchema = z.object({
 id: z.string().uuid(),
 user_id: z.string(),
 house_id: z.string().uuid(),
 source: JoinRequestSourceSchema,
 status: JoinRequestStatusSchema,
 rejection_reason: z.string(),
 created_at: z.string().datetime({offset:true}).nullable().optional(),
 reviewed_at: z.string().datetime({offset:true}).nullable().optional(),
 display_name: z.string(),
});
export type JoinRequest = z.infer<typeof JoinRequestSchema>;
export const HouseInvitationSchema = z.object({
 id: z.string().uuid(),
 house_id: z.string().uuid(),
 created_by: z.string().uuid(),
 expires_at: z.string().datetime({offset:true}).nullable().optional(),
 max_uses: z.number().int(),
 used_count: z.number().int(),
 status: InvitationStatusSchema,
 created_at: z.string().datetime({offset:true}).nullable().optional(),
});
export type HouseInvitation = z.infer<typeof HouseInvitationSchema>;
export const CreatedInvitationSchema = z.object({
 invitation: HouseInvitationSchema,
 token: z.string(),
 deep_link: z.string(),
});
export type CreatedInvitation = z.infer<typeof CreatedInvitationSchema>;
export const ChairmanTransferSchema = z.object({
 id: z.string().uuid(),
 house_id: z.string().uuid(),
 current_chairman_user_id: z.string().uuid(),
 target_user_id: z.string().uuid(),
 status: ChairmanTransferStatusSchema,
 expires_at: z.string().datetime({offset:true}).nullable().optional(),
 created_at: z.string().datetime({offset:true}).nullable().optional(),
});
export type ChairmanTransfer = z.infer<typeof ChairmanTransferSchema>;
export const HouseSummarySchema = z.object({
 id: z.string().uuid(),
 name: z.string(),
 address: z.string(),
 city: z.string(),
 has_chairman: z.boolean(),
 join_available: z.boolean(),
});
export type HouseSummary = z.infer<typeof HouseSummarySchema>;
export const HouseMemberSchema = z.object({
 id: z.string().uuid(),
 user_id: z.string(),
 house_id: z.string().uuid(),
 display_name: z.string(),
 role: z.string(),
 status: z.string(),
});
export type HouseMember = z.infer<typeof HouseMemberSchema>;
export const HouseAccessStateSchema = z.object({
 platform_admin: z.boolean(),
 pending_registrations: z.number().int(),
 pending_join_requests: z.number().int(),
 incoming_join_requests: z.number().int(),
 can_manage_active_house: z.boolean(),
 can_register_house: z.boolean(),
});
export type HouseAccessState = z.infer<typeof HouseAccessStateSchema>;
export const NotificationPreferencesSchema = z.object({
 notifications_enabled: z.boolean(),
 issue_notifications_enabled: z.boolean(),
 announcement_notifications_enabled: z.boolean(),
 membership_notifications_enabled: z.boolean(),
 bot_notifications_enabled: z.boolean(),
});
export type NotificationPreferences = z.infer<typeof NotificationPreferencesSchema>;
export const HouseRegistrationListSchema = z.object({
 items: HouseRegistrationSchema.array(),
});
export type HouseRegistrationList = z.infer<typeof HouseRegistrationListSchema>;
export const JoinRequestListSchema = z.object({
 items: JoinRequestSchema.array(),
});
export type JoinRequestList = z.infer<typeof JoinRequestListSchema>;
export const HouseInvitationListSchema = z.object({
 items: HouseInvitationSchema.array(),
});
export type HouseInvitationList = z.infer<typeof HouseInvitationListSchema>;
export const ChairmanTransferListSchema = z.object({
 items: ChairmanTransferSchema.array(),
});
export type ChairmanTransferList = z.infer<typeof ChairmanTransferListSchema>;
export const HouseMemberListSchema = z.object({
 items: HouseMemberSchema.array(),
});
export type HouseMemberList = z.infer<typeof HouseMemberListSchema>;
export const HouseSearchResultSchema = z.object({
 items: HouseSummarySchema.array(),
});
export type HouseSearchResult = z.infer<typeof HouseSearchResultSchema>;
export const houseApi = {
 ListPlatformUsers: (args: {query: string}, signal?: AbortSignal) => request(`/admin/users?query=${encodeURIComponent(args.query)}`, PlatformUserListSchema, { signal }),
 GrantChairmanPermission: (args: {user_id: string}, key?: string) => request(`/admin/users/${encodeURIComponent(args.user_id)}/chairman`, PlatformUserSchema, { method: "POST", key, body: {} }),
 RevokeChairmanPermission: (args: {user_id: string}, key?: string) => request(`/admin/users/${encodeURIComponent(args.user_id)}/chairman`, PlatformUserSchema, { method: "DELETE", key, body: {} }),
 ListAdminHouses: (args: {query: string}, signal?: AbortSignal) => request(`/admin/houses?query=${encodeURIComponent(args.query)}`, AdminHouseListSchema, { signal }),
 AssignHouseChairman: (args: {house_id: string, target_user_id: string}, key?: string) => request(`/admin/houses/${encodeURIComponent(args.house_id)}/chairman`, AdminHouseSchema, { method: "PUT", key, body: {target_user_id: args.target_user_id} }),
 RemoveHouseChairman: (args: {house_id: string}, key?: string) => request(`/admin/houses/${encodeURIComponent(args.house_id)}/chairman`, AdminHouseSchema, { method: "DELETE", key, body: {} }),
 CreateHouseRegistration: (args: {name: string, address: string, city: string}, key?: string) => request(`/house-registrations`, HouseRegistrationSchema, { method: "POST", key, body: {name: args.name,address: args.address,city: args.city} }),
 GetHouseRegistration: (args: {id: string}, signal?: AbortSignal) => request(`/house-registrations/${encodeURIComponent(args.id)}`, HouseRegistrationSchema, { signal }),
 ListMyHouseRegistrations: (signal?: AbortSignal) => request(`/house-registrations`, HouseRegistrationListSchema, { signal }),
 CancelHouseRegistration: (args: {id: string}, key?: string) => request(`/house-registrations/${encodeURIComponent(args.id)}/cancel`, HouseRegistrationSchema, { method: "POST", key, body: {} }),
 ListPendingHouseRegistrations: (signal?: AbortSignal) => request(`/admin/house-registrations`, HouseRegistrationListSchema, { signal }),
 ApproveHouseRegistration: (args: {id: string, reason: string}, key?: string) => request(`/admin/house-registrations/${encodeURIComponent(args.id)}/approve`, HouseRegistrationSchema, { method: "POST", key, body: {reason: args.reason} }),
 RejectHouseRegistration: (args: {id: string, reason: string}, key?: string) => request(`/admin/house-registrations/${encodeURIComponent(args.id)}/reject`, HouseRegistrationSchema, { method: "POST", key, body: {reason: args.reason} }),
 SearchHouses: (args: {query: string}, signal?: AbortSignal) => request(`/houses/search?query=${encodeURIComponent(args.query)}`, HouseSearchResultSchema, { signal }),
 CreateJoinRequest: (args: {house_id: string}, key?: string) => request(`/houses/${encodeURIComponent(args.house_id)}/join-requests`, JoinRequestSchema, { method: "POST", key, body: {} }),
 ListMyJoinRequests: (signal?: AbortSignal) => request(`/join-requests`, JoinRequestListSchema, { signal }),
 CancelJoinRequest: (args: {id: string}, key?: string) => request(`/join-requests/${encodeURIComponent(args.id)}/cancel`, JoinRequestSchema, { method: "POST", key, body: {} }),
 ListHouseJoinRequests: (signal?: AbortSignal) => request(`/chairman/join-requests`, JoinRequestListSchema, { signal }),
 ApproveJoinRequest: (args: {id: string, reason: string}, key?: string) => request(`/chairman/join-requests/${encodeURIComponent(args.id)}/approve`, JoinRequestSchema, { method: "POST", key, body: {reason: args.reason} }),
 RejectJoinRequest: (args: {id: string, reason: string}, key?: string) => request(`/chairman/join-requests/${encodeURIComponent(args.id)}/reject`, JoinRequestSchema, { method: "POST", key, body: {reason: args.reason} }),
 CreateHouseInvitation: (args: {expires_in_hours: number, max_uses: number}, key?: string) => request(`/chairman/invitations`, CreatedInvitationSchema, { method: "POST", key, body: {expires_in_hours: args.expires_in_hours,max_uses: args.max_uses} }),
 ListHouseInvitations: (signal?: AbortSignal) => request(`/chairman/invitations`, HouseInvitationListSchema, { signal }),
 GetHouseInvitation: (args: {id: string}, signal?: AbortSignal) => request(`/invitations/${encodeURIComponent(args.id)}`, HouseInvitationSchema, { signal }),
 RevokeHouseInvitation: (args: {id: string}, key?: string) => request(`/chairman/invitations/${encodeURIComponent(args.id)}/revoke`, HouseInvitationSchema, { method: "POST", key, body: {} }),
 RedeemHouseInvitation: (args: {token: string}, key?: string) => request(`/invitations/redeem`, JoinRequestSchema, { method: "POST", key, body: {token: args.token} }),
 PreviewHouseInvitation: (args: {token: string}, key?: string) => request(`/invitations/preview`, HouseSummarySchema, { method: "POST", key, body: {token: args.token} }),
 CreateChairmanTransfer: (args: {target_user_id: string}, key?: string) => request(`/chairman/transfers`, ChairmanTransferSchema, { method: "POST", key, body: {target_user_id: args.target_user_id} }),
 ListChairmanTransfers: (signal?: AbortSignal) => request(`/chairman/transfers`, ChairmanTransferListSchema, { signal }),
 AcceptChairmanTransfer: (args: {id: string}, key?: string) => request(`/chairman/transfers/${encodeURIComponent(args.id)}/accept`, ChairmanTransferSchema, { method: "POST", key, body: {} }),
 RejectChairmanTransfer: (args: {id: string}, key?: string) => request(`/chairman/transfers/${encodeURIComponent(args.id)}/reject`, ChairmanTransferSchema, { method: "POST", key, body: {} }),
 CancelChairmanTransfer: (args: {id: string}, key?: string) => request(`/chairman/transfers/${encodeURIComponent(args.id)}/cancel`, ChairmanTransferSchema, { method: "POST", key, body: {} }),
 ListHouseMembers: (signal?: AbortSignal) => request(`/chairman/members`, HouseMemberListSchema, { signal }),
 DeactivateMembership: (args: {id: string, platform_admin_override?: boolean}, key?: string) => request(`/chairman/members/${encodeURIComponent(args.id)}/deactivate`, HouseMemberSchema, { method: "POST", key, body: {platform_admin_override: args.platform_admin_override} }),
 ReactivateMembership: (args: {id: string, platform_admin_override?: boolean}, key?: string) => request(`/chairman/members/${encodeURIComponent(args.id)}/reactivate`, HouseMemberSchema, { method: "POST", key, body: {platform_admin_override: args.platform_admin_override} }),
 RemoveMembership: (args: {id: string, platform_admin_override?: boolean}, key?: string) => request(`/chairman/members/${encodeURIComponent(args.id)}`, HouseMemberSchema, { method: "DELETE", key, body: {platform_admin_override: args.platform_admin_override} }),
 GetHouseAccessState: (signal?: AbortSignal) => request(`/house-access`, HouseAccessStateSchema, { signal }),
 GetNotificationPreferences: (signal?: AbortSignal) => request(`/notifications/settings`, NotificationPreferencesSchema, { signal }),
 UpdateNotificationPreferences: (args: {notifications_enabled: boolean, issue_notifications_enabled: boolean, announcement_notifications_enabled: boolean, membership_notifications_enabled: boolean, bot_notifications_enabled: boolean}, key?: string) => request(`/notifications/settings`, NotificationPreferencesSchema, { method: "PUT", key, body: {notifications_enabled: args.notifications_enabled,issue_notifications_enabled: args.issue_notifications_enabled,announcement_notifications_enabled: args.announcement_notifications_enabled,membership_notifications_enabled: args.membership_notifications_enabled,bot_notifications_enabled: args.bot_notifications_enabled} }),
};
