import json,re
from pathlib import Path
root=Path(__file__).resolve().parents[1]
data=json.loads((root/'contracts/house-workflow.json').read_text(encoding='utf-8'))
def prefix(n):return re.sub(r'(?<!^)(?=[A-Z])','_',n).upper()
src="// Generated by scripts/generate-house-web.py.\nimport { z } from 'zod';\nimport { request } from './client';\n"
for name,values in data['enums'].items():src+=f'const {name}Schema = z.enum('+json.dumps([prefix(name)+'_'+v for v in values])+');\n'
for name,fields in data['entities'].items():
    if name.startswith('NotificationRecipient'):continue
    src+=f'export const {name}Schema = z.object({{\n'
    for t,f in fields:
        if t=='string':
            rule="z.string()"
            if f!='max_user_id' and (f=='id' or f.endswith('_user_id') or f=='house_id' or f=='created_by'):rule='z.string().uuid()'
            if f in ['resulting_house_id','chairman_user_id']:rule="z.union([z.string().uuid(),z.literal('')])"
        elif t=='bool':rule='z.boolean()'
        elif t=='int32':rule='z.number().int()'
        elif t=='google.protobuf.Timestamp':rule='z.string().datetime({offset:true}).nullable().optional()'
        elif t.startswith('repeated '):rule=t[9:]+'Schema.array()'
        else:rule=t+'Schema'
        src+=f' {f}: {rule},\n'
    src+='});\n'+f'export type {name} = z.infer<typeof {name}Schema>;\n'
src+='export const houseApi = {\n'
for o in data['operations']:
    fields=o['fields'];pathfields=re.findall(r'{(\w+)}',o['path']);body=[f for t,f in fields if f not in pathfields]
    args=', '.join(f'{f}'+('?' if f=='platform_admin_override' else '')+': '+{'string':'string','int32':'number','bool':'boolean'}[t] for t,f in fields)
    signature=f'(args: {{{args}}}, ' if fields else '(' 
    signature+= 'signal?: AbortSignal)' if o['method']=='GET' else 'key?: string)'
    path=re.sub(r'{(\w+)}',r'${encodeURIComponent(args.\1)}',o['path'])
    if o['method']=='GET' and body:path+='?'+ '&'.join(f'{f}=${{encodeURIComponent(args.{f})}}' for f in body)
    options='{ signal }' if o['method']=='GET' else '{ method: '+json.dumps(o['method'])+', key, body: {'+','.join(f'{f}: args.{f}' for f in body)+'} }'
    src+=f' {o["name"]}: {signature} => request(`{path}`, {o["response"]}Schema, {options}),\n'
src+='};\n'
(root/'web/miniapp/src/shared/api/house.ts').write_text(src,encoding='utf-8')
