"""Additive house workflow contracts and transport bindings; protobuf code is generated by Buf."""
from pathlib import Path
import json,re
ROOT=Path(__file__).resolve().parents[1]
ops=[]
def op(name,fields,response,method,path,access='session',code=200):
    ops.append(dict(name=name,fields=fields,response=response,method=method,path=path,access=access,code=code))
s='string';i='int32';b='bool'
op('CreateHouseRegistration',[(s,'name'),(s,'address'),(s,'city')],'HouseRegistration','POST','/house-registrations',code=202)
op('GetHouseRegistration',[(s,'id')],'HouseRegistration','GET','/house-registrations/{id}')
op('ListMyHouseRegistrations',[],'HouseRegistrationList','GET','/house-registrations')
op('CancelHouseRegistration',[(s,'id')],'HouseRegistration','POST','/house-registrations/{id}/cancel')
op('ListPendingHouseRegistrations',[],'HouseRegistrationList','GET','/admin/house-registrations','admin')
for action in ['Approve','Reject']:
    op(action+'HouseRegistration',[(s,'id'),(s,'reason')],'HouseRegistration','POST','/admin/house-registrations/{id}/'+action.lower(),'admin')
op('SearchHouses',[(s,'query')],'HouseSearchResult','GET','/houses/search')
op('CreateJoinRequest',[(s,'house_id')],'JoinRequest','POST','/houses/{house_id}/join-requests',code=202)
op('ListMyJoinRequests',[],'JoinRequestList','GET','/join-requests')
op('CancelJoinRequest',[(s,'id')],'JoinRequest','POST','/join-requests/{id}/cancel')
op('ListHouseJoinRequests',[],'JoinRequestList','GET','/chairman/join-requests','manager')
for action in ['Approve','Reject']:
    op(action+'JoinRequest',[(s,'id'),(s,'reason')],'JoinRequest','POST','/chairman/join-requests/{id}/'+action.lower(),'manager')
op('CreateHouseInvitation',[(i,'expires_in_hours'),(i,'max_uses')],'CreatedInvitation','POST','/chairman/invitations','manager',201)
op('ListHouseInvitations',[],'HouseInvitationList','GET','/chairman/invitations','manager')
op('GetHouseInvitation',[(s,'id')],'HouseInvitation','GET','/invitations/{id}','manager')
op('RevokeHouseInvitation',[(s,'id')],'HouseInvitation','POST','/chairman/invitations/{id}/revoke','manager')
op('RedeemHouseInvitation',[(s,'token')],'JoinRequest','POST','/invitations/redeem',code=202)
op('PreviewHouseInvitation',[(s,'token')],'HouseSummary','POST','/invitations/preview')
op('CreateChairmanTransfer',[(s,'target_user_id')],'ChairmanTransfer','POST','/chairman/transfers','manager',202)
op('ListChairmanTransfers',[],'ChairmanTransferList','GET','/chairman/transfers')
for action in ['Accept','Reject','Cancel']:
    op(action+'ChairmanTransfer',[(s,'id')],'ChairmanTransfer','POST','/chairman/transfers/{id}/'+action.lower())
op('ListHouseMembers',[],'HouseMemberList','GET','/chairman/members','manager')
for action in ['Deactivate','Reactivate','Remove']:
    op(action+'Membership',[(s,'id'),(b,'platform_admin_override')],'HouseMember','DELETE' if action=='Remove' else 'POST','/chairman/members/{id}'+('' if action=='Remove' else '/'+action.lower()),'manager')
op('GetHouseAccessState',[],'HouseAccessState','GET','/house-access')
prefs=[(b,x) for x in ['notifications_enabled','issue_notifications_enabled','announcement_notifications_enabled','membership_notifications_enabled','bot_notifications_enabled']]
op('GetNotificationPreferences',[],'NotificationPreferences','GET','/notifications/settings')
op('UpdateNotificationPreferences',prefs,'NotificationPreferences','PUT','/notifications/settings')
# Internal worker-only operation is deliberately not routed through HTTP.
internal=[dict(name='ListNotificationRecipients',fields=[(s,'house_id'),(s,'user_id'),(s,'category'),(s,'after_user_id')],response='NotificationRecipientList')]
entities={
'HouseRegistration':[(s,'id'),(s,'applicant_user_id'),(s,'requested_name'),(s,'original_address'),(s,'city'),('HouseRegistrationStatus','status'),(s,'resulting_house_id'),(s,'rejection_reason'),('google.protobuf.Timestamp','created_at'),('google.protobuf.Timestamp','reviewed_at')],
'JoinRequest':[(s,'id'),(s,'user_id'),(s,'house_id'),('JoinRequestSource','source'),('JoinRequestStatus','status'),(s,'rejection_reason'),('google.protobuf.Timestamp','created_at'),('google.protobuf.Timestamp','reviewed_at')],
'HouseInvitation':[(s,'id'),(s,'house_id'),(s,'created_by'),('google.protobuf.Timestamp','expires_at'),(i,'max_uses'),(i,'used_count'),('InvitationStatus','status'),('google.protobuf.Timestamp','created_at')],
'CreatedInvitation':[('HouseInvitation','invitation'),(s,'token'),(s,'deep_link')],
'ChairmanTransfer':[(s,'id'),(s,'house_id'),(s,'current_chairman_user_id'),(s,'target_user_id'),('ChairmanTransferStatus','status'),('google.protobuf.Timestamp','expires_at'),('google.protobuf.Timestamp','created_at')],
'HouseSummary':[(s,'id'),(s,'name'),(s,'address'),(s,'city'),(b,'has_chairman'),(b,'join_available')],
'HouseMember':[(s,'id'),(s,'user_id'),(s,'house_id'),(s,'display_name'),(s,'role'),(s,'status')],
'HouseAccessState':[(b,'platform_admin'),(i,'pending_registrations'),(i,'pending_join_requests'),(i,'incoming_join_requests'),(b,'can_manage_active_house')],
'NotificationPreferences':prefs,
'NotificationRecipient':[(s,'user_id'),(s,'max_user_id')],
}
for a,c in [('HouseRegistration','HouseRegistration'),('JoinRequest','JoinRequest'),('HouseInvitation','HouseInvitation'),('ChairmanTransfer','ChairmanTransfer'),('HouseMember','HouseMember'),('NotificationRecipient','NotificationRecipient')]:entities[a+'List']=[('repeated '+c,'items')]
entities['HouseRegistration'].append((s,'applicant_display_name'))
entities['JoinRequest'].append((s,'display_name'))
entities['HouseSearchResult']=[('repeated HouseSummary','items')]
enums={'HouseRegistrationStatus':['PENDING','APPROVED','REJECTED','CANCELLED'],'JoinRequestStatus':['PENDING','APPROVED','REJECTED','CANCELLED'],'InvitationStatus':['ACTIVE','EXPIRED','REVOKED','EXHAUSTED'],'ChairmanTransferStatus':['PENDING','ACCEPTED','REJECTED','CANCELLED','EXPIRED'],'JoinRequestSource':['SEARCH','INVITE','ADMIN']}
def prefix(n):return re.sub(r'(?<!^)(?=[A-Z])','_',n).upper()
def message(name,fields):return 'message '+name+' {\n'+''.join(f'  {t} {n} = {k};\n' for k,(t,n) in enumerate(fields,1))+'}\n'
block='\n// House onboarding (additive contract).\n'
for n,values in enums.items():block+='enum '+n+' {\n'+''.join(f'  {prefix(n)}_{v} = {k};\n' for k,v in enumerate(['UNSPECIFIED']+values))+'}\n'
for n,fields in entities.items():block+=message(n,fields)
for o in ops+internal:block+=message(o['name']+'Request',o['fields'])
block+='service HouseService {\n'+''.join(f'  rpc {o["name"]}({o["name"]}Request) returns ({o["response"]});\n' for o in ops+internal)+'}\n'
p=ROOT/'contracts/proto/smartquarter/identity/v1/identity.proto'
src=p.read_text(encoding='utf-8').split('// House onboarding (additive contract).')[0].rstrip()
p.write_text(src+'\n'+block,encoding='utf-8',newline='\n')
(ROOT/'contracts/house-workflow.json').write_text(json.dumps(dict(operations=ops,entities=entities,enums=enums),ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
transport='''// Code generated by scripts/generate-house-contracts.py; DO NOT EDIT.
package grpc
import("context"; "encoding/json"; "github.com/ZheglY/SmartQuarter/services/identity-service/internal/house"; pb "github.com/ZheglY/SmartQuarter/services/identity-service/internal/gen/smartquarter/identity/v1"; "google.golang.org/protobuf/encoding/protojson"; "google.golang.org/protobuf/proto"; "google.golang.org/grpc/codes"; "google.golang.org/grpc/status")
type HouseHandler struct {pb.UnimplementedHouseServiceServer; Workflow *house.Service}
func (h *HouseHandler) call(ctx context.Context, op string, req, res proto.Message) error {
 raw,e:= (protojson.MarshalOptions{UseProtoNames:true,EmitDefaultValues:true}).Marshal(req); if e!=nil{return status.Error(codes.InvalidArgument,"invalid command")}; var c house.Command; if json.Unmarshal(raw,&c)!=nil{return status.Error(codes.InvalidArgument,"invalid command")}; data,e:=h.Workflow.Execute(ctx,op,c); if e!=nil{return e}; if e=(protojson.UnmarshalOptions{DiscardUnknown:true}).Unmarshal(data,res); e!=nil{return status.Error(codes.Internal,"invalid workflow response")}; return nil
}
'''
for o in ops+internal:
 n=o['name'];r=o['response'];transport+=f'func(h *HouseHandler) {n}(ctx context.Context,req *pb.{n}Request)(*pb.{r},error){{res:=new(pb.{r});err:=h.call(ctx,"{n}",req,res);return res,err}}\n'
(ROOT/'services/identity-service/internal/transport/grpc/house_generated.go').write_text(transport,encoding='utf-8')
print('Generated additive contracts:',len(ops),'REST operations')
