"""Generate explicit typed HTTP adapters from the reviewed house route registry."""
import json,re
from pathlib import Path
root=Path(__file__).resolve().parents[1]
registry=json.loads((root/'contracts/house-workflow.json').read_text(encoding='utf-8'))
def field(n): return ''.join(x.title() for x in n.split('_'))
src='''// Code generated by scripts/generate-house-http.py; DO NOT EDIT.
package http
import("net/http"; "net/url"; "encoding/json"; "google.golang.org/protobuf/encoding/protojson"; "google.golang.org/protobuf/proto"; ipb "github.com/ZheglY/SmartQuarter/services/max-gateway/internal/gen/smartquarter/identity/v1"; "github.com/ZheglY/SmartQuarter/services/max-gateway/internal/identity")
func(a *API) houseResponse(w http.ResponseWriter,r *http.Request,code int,v proto.Message,e error){if e!=nil{a.rpcError(w,r,e);return};raw,e:=(protojson.MarshalOptions{UseProtoNames:true,EmitDefaultValues:true}).Marshal(v);if e!=nil{a.fail(w,r,502,"INVALID_UPSTREAM_RESPONSE","invalid Identity response");return};write(w,code,json.RawMessage(raw))}
func(a *API) houseRoutes(mux *http.ServeMux){
'''
for o in registry['operations']:
    n=o['name']; handler='a.house'+n
    # Fresh permissions live in Identity, including platform-admin bootstrap
    # and recipients accepting transfers without chairman privileges.
    if o['method']!='GET': handler='a.idempotent('+handler+')'
    if o['access'] in ['manager','admin','chairman']: handler='a.housePermission("'+o['access']+'",'+handler+')'
    src+=f' mux.HandleFunc("{o["method"]} /api/v1{o["path"]}",a.origin(a.authenticate(false,false,{handler})))\n'
src+='}\n'
for o in registry['operations']:
    n=o['name'];pathfields=re.findall(r'{(\w+)}',o['path']);body=[(t,f) for t,f in o['fields'] if f not in pathfields]
    src+=f'func(a *API) house{n}(w http.ResponseWriter,r *http.Request){{\n if a.House==nil{{a.fail(w,r,503,"DEPENDENCY_UNAVAILABLE","house workflow unavailable");return}}\n'
    for f in pathfields:
        src+=f' if !identity.ValidID(r.PathValue("{f}")){{a.fail(w,r,400,"INVALID_ARGUMENT","invalid resource id");return}}\n'
    if o['method']!='GET':
        src+='var body struct{'+''.join(f'{field(f)} '+('bool' if f=='platform_admin_override' else {'string':'string','int32':'int32','bool':'*bool'}[t])+f' `json:"{f}"`; ' for t,f in body)+'}\nif !a.decode(w,r,&body){return}\n'
        for t,f in body:
            if t=='bool' and f!='platform_admin_override':src+=f'if body.{field(f)}==nil{{a.fail(w,r,400,"INVALID_ARGUMENT","all preferences required");return}}\n'
    src+=f'req:=&ipb.{n}Request{{'+','.join(field(f)+':'+(f'r.PathValue("{f}")' if f in pathfields else f'r.URL.Query().Get("{f}")' if o['method']=='GET' else ('*' if t=='bool' and f!='platform_admin_override' else '')+f'body.{field(f)}') for t,f in o['fields'])+'}\n'
    src+=f'v,e:=a.House.{n}(r.Context(),req);'
    if n=='CreateHouseInvitation':src+='if e==nil && a.Config.BotUsername!="" {v.DeepLink="https://max.ru/"+url.PathEscape(a.Config.BotUsername)+"?startapp=invite_"+v.Token};'
    src+=f'a.houseResponse(w,r,{o["code"]},v,e)\n}}\n'
(root/'services/max-gateway/internal/transport/http/house_generated.go').write_text(src,encoding='utf-8')
